### ISSUE TITLE
Metadata Problem

### ISSUE THREAD

**Issue by ManuSuresh256** [lapoozza/lapzbot#8]
Incomplete Song Metadata causes playlist to show errors

**Comment by JewelMahanta** [comment]
Its because the way the bot is coded, it requires the metdata to have 'Title' and 'Artist' tags present. If any of these are missing, it will cause an error. You will be able to see the songs with incomplete metadata from the command prompt window. Either remove these from audio_library folder or edit the metadata yourself.

**Comment by JewelMahanta** [comment]
Reopening this issue. Need a better fix.
